name: Send Email

on:
  schedule:
   - cron: "39 22 * * 2"

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests smtplib pytz pandas python-dotenv

      - name: Run script to send email
        run: python journal.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SPRINGER_API_KEY: ${{ secrets.SPRINGER_API_KEY }}
          IEEE_API_KEY: ${{ secrets.IEEE_API_KEY }}

      # You can add additional steps as needed
