name: Run Journal Script

on:
  schedule:
   - cron: "20 21 * * 2"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  

      - name: Install dependencies
        run: |
         pip install -r requirements.txt

      
      - name: Send the journals to the subscribers
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SPRINGER_API_KEY: ${{ secrets.SPRINGER_API_KEY }}
        
        run: |
         python journal.py
