name: Send Journal Emails

on:
  schedule:
    - cron: "52 23 * * 2"  # Run every Saturday at 8:00 AM (UTC time)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Run Python script
        run: |
          python journal.py