name: weekly-report

on:
  schedule:
    -cron: '1 * * * *' 
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: 3.x
        -name: Run email code
          env:
            EMAIL_USER: ${{secrets.EMAIL_USER}}
            EMAIL_USER: ${{secrets.EMAIL_PASS}}
            EMAIL_USER: ${{secrets.SPRINGER_API_KEY}}
          run: python journal.py          